Improved login to registry #3259

diff --git a/docker-setup b/docker-setup
--- a/docker-setup
+++ b/docker-setup
@@ -61,9 +61,24 @@ if ! type yq >/dev/null 2>&1 || test "$(yq --version | cut -d' ' -f4)" != "${YQ_
         https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64
 fi
 
+if test -z "${DOCKER_CONFIG}"; then
+    export DOCKER_CONFIG="${HOME}/.docker"
+fi
+
 if ! regctl registry config | jq --exit-status --arg registry "${REGISTRY}" 'to_entries[] | select(.key == $registry)' >/dev/null 2>&1; then
-    if test -n "${REGISTRY_USERNAME}" && test -n "${REGISTRY_PASSWORD}"; then
+    >&2 echo "WARNING: regctl does not know how to login to ${REGISTRY}"
+
+    if test -f "${DOCKER_CONFIG}/config.json" && jq --exit-status --arg registry ghcr.io '.auths | to_entries[] | select(.key == $registry)' "${DOCKER_CONFIG}/config.json" >/dev/null; then
+        >&2 echo "${emoji_auth} Logging in to ${REGISTRY} using credentials from Docker config.json"
+        AUTH="$(jq -r '.auths | to_entries[] | select(.key == "ghcr.io") | .value.auth' "${DOCKER_CONFIG}/config.json" | base64 -d)"
+        regctl registry login ${REGISTRY} --user "${AUTH#*:}" --pass "${AUTH%%:*}"
+
+    elif test -n "${REGISTRY_USERNAME}" && test -n "${REGISTRY_PASSWORD}"; then
+        >&2 echo "${emoji_Auth} Logging in to ${REGISTRY} using credentials from environment variables"
         regctl registry login ${REGISTRY} --user "${REGISTRY_USERNAME}" --pass "${REGISTRY_PASSWORD}"
+
+    elif ! test -t 1; then
+        >&2 echo "${emoji_auth} No console available. Unable to login to ${REGISTRY}."
 
     else
         echo "${emoji_auth} Logging in to ${REGISTRY}"
@@ -82,10 +97,6 @@ if ! test -f "${docker_setup_tools_file}"; then
         regctl blob get "${REGISTRY}/${REPOSITORY_PREFIX}metadata:${docker_setup_version}" "${DIGEST}" \
         | tar --extract --gzip --directory="${docker_setup_cache}" --no-same-owner
     done
-fi
-
-if test -z "${DOCKER_CONFIG}"; then
-    export DOCKER_CONFIG="${HOME}/.docker"
 fi
 
 declare -A tools_install
