Implemented conflicts #4848

diff --git a/docker-setup b/docker-setup
--- a/docker-setup
+++ b/docker-setup
@@ -16,7 +16,7 @@ if test -t 1; then
                  https://github.com/nicholasdille/docker-setup
 --------------------------------------------------------------
 This script will install Docker Engine as well as useful tools
-from the container ecosystem.
+from the container ecosystem and beyond.
 
 EOF
 fi
@@ -453,6 +453,37 @@ function check_tools() {
     profile "Done warming cache"
 }
 
+function has_conflicts() {
+    conflict_found=false
+
+    for name in ${install_tools}; do
+        conflicts="$(
+            jq --raw-output 'select(.conflicts_with != null) | .conflicts_with[]' <<<"${tool_json[${name}]}"
+        )"
+        #echo "Conflicts for ${name}: ${conflicts}"
+
+        for conflict in ${conflicts}; do
+            debug "Checking conflict between planned ${name} and installed ${conflict}"
+            if ${tool_installed[${conflict}]}; then
+                echo "Warning: Conflict between requested ${name} and installed ${conflict}"
+                conflict_found=true
+            fi
+
+            debug "Checking conflict between planned ${name} and planned ${conflict}"
+            if echo "${install_tools}" | grep -qE "(^|\s)${conflict}(\s|$)"; then
+                echo "Warning: Conflict between planned ${name} and planned ${conflict}"
+                conflict_found=true
+            fi
+        done
+    done
+
+    if ! ${conflict_found}; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 function show_help() {
     cat <<EOF
 docker-setup
@@ -487,6 +518,7 @@ warm_cache
 
 target=/usr/local
 : "${include_deps:=true}"
+: "${check_conflicts:=true}"
 : "${reinstall:=false}"
 : "${cron:=true}"
 while test "$#" -gt 0; do
@@ -568,6 +600,15 @@ while test "$#" -gt 0; do
                 install_tools="${selected_tools}"
             fi
             profile "Done resolving dependencies"
+
+            check_tools
+            profile "Done checking tools"
+
+            if ${check_conflicts} && has_conflicts; then
+                echo "ERROR: Conflicts detected."
+                exit 1
+            fi
+            profile "Done checking conflicts"
             ;;
 
         --tags|--tags=*)
@@ -613,6 +654,10 @@ while test "$#" -gt 0; do
                 warning "Place --[no-]deps before tools/tags selectors."
             fi
             include_deps=false
+            ;;
+
+        --ignore-conflicts)
+            check_conflicts=false
             ;;
 
         --cron)
@@ -670,7 +715,6 @@ while test "$#" -gt 0; do
             ;;
 
         plan|p|status|s)
-            check_tools
             echo
             for name in ${install_tools}; do
                 tool_version_string="${tool_operator[${name}]}${tool_version[${name}]}"
@@ -771,7 +815,6 @@ while test "$#" -gt 0; do
                 debug "Using prefix ${prefix}"
                 mkdir -p "${prefix}"
             fi
-            check_tools
             for tool in ${install_tools}; do
                 if ! ${reinstall} && ${tool_installed[${tool}]} && ${tool_version_matches[${tool}]}; then
                     echo -e "${green}${emoji_done}${reset} Nothing to do for ${tool} ${tool_version[${tool}]}"
