Fixed mixed up architectures #6610

diff --git a/tools/goreleaser/Dockerfile.template b/tools/goreleaser/Dockerfile.template
--- a/tools/goreleaser/Dockerfile.template
+++ b/tools/goreleaser/Dockerfile.template
@@ -4,28 +4,30 @@ ARG ref=main
 
 FROM ghcr.io/nicholasdille/docker-setup/cosign:${ref} AS cosign
 
-FROM --platform=amd64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS download
-ARG name
-ARG version
-RUN <<EOF
-echo "### Downloading goreleaser ${version}"
-curl --silent --location --fail --output "goreleaser_Linux_${alt_arch}.tar.gz" "https://github.com/goreleaser/goreleaser/releases/download/v${version}/goreleaser_Linux_${arch}.tar.gz"
-EOF
-
-FROM --platform=arm64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS download
-ARG name
-ARG version
-RUN <<EOF
-set -x
-echo "### Downloading goreleaser ${version}"
-curl --silent --location --fail --output "goreleaser_Linux_${alt_arch}.tar.gz" "https://github.com/goreleaser/goreleaser/releases/download/v${version}/goreleaser_Linux_${alt_arch}.tar.gz"
-EOF
-
-FROM download AS prepare
+FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
 COPY --link --from=cosign / /
+WORKDIR /tmp/goreleaser
 ARG name
 ARG version
 RUN <<EOF
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+echo "### Downloading goreleaser ${version}"
+curl --silent --location --fail --remote-name "https://github.com/goreleaser/goreleaser/releases/download/v${version}/goreleaser_Linux_${arch_suffix}.tar.gz"
+
 echo "### Downloading checksums"
 curl --silent --location --fail --remote-name "https://github.com/goreleaser/goreleaser/releases/download/v${version}/checksums.txt"
 sha256sum --check --ignore-missing checksums.txt
@@ -50,7 +52,7 @@ COSIGN_EXPERIMENTAL=1 cosign verify-blob checksums.txt \
     --certificate-github-workflow-sha "${SHA}"
 
 echo "### Unpacking"
-tar --extract --gzip --file "goreleaser_Linux_${alt_arch}.tar.gz" --directory="${prefix}${target}/bin/" --no-same-owner \
+tar --extract --gzip --file="goreleaser_Linux_${arch_suffix}.tar.gz" --directory="${prefix}${target}/bin/" --no-same-owner \
     goreleaser \
     manpages \
     completions
