Fix release asset name

diff --git a/tools/helmify/Dockerfile.template b/tools/helmify/Dockerfile.template
--- a/tools/helmify/Dockerfile.template
+++ b/tools/helmify/Dockerfile.template
@@ -1,12 +1,26 @@
 #syntax=docker/dockerfile:1.5.2
 
 ARG ref=main
-FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
 
+FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
 ARG name
 ARG version
-
 RUN <<EOF
-curl --silent --location --fail "https://github.com/arttor/helmify/releases/download/v${version}/helmify_${version}_Linux_64-bit.tar.gz" \
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
+
+curl --silent --location --fail "https://github.com/arttor/helmify/releases/download/v${version}/helmify_Linux_${arch_suffix}.tar.gz" \
 | tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner
 EOF
