Fixed multi-arch for wasmer

diff --git a/tools/wasmer/Dockerfile.template b/tools/wasmer/Dockerfile.template
--- a/tools/wasmer/Dockerfile.template
+++ b/tools/wasmer/Dockerfile.template
@@ -6,7 +6,19 @@ FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
 ARG name
 ARG version
 RUN <<EOF
-curl --silent --location --fail "https://github.com/wasmerio/wasmer/releases/download/v${version}/wasmer-linux-${alt_arch}.tar.gz" \
+case "${alt_arch}" in
+    amd64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    arm64)
+        export arch_suffix="${arch}"
+        ;;
+    *)
+        echo "ERROR: Unknown architecture (${alt_arch})."
+        exit 1
+        ;;
+esac
+curl --silent --location --fail "https://github.com/wasmerio/wasmer/releases/download/v${version}/wasmer-linux-${arch_suffix}.tar.gz" \
 | tar --extract --gzip --directory="${prefix}${target}" --no-same-owner \
     bin
 EOF
