Fixed mixup in architecture #6610

diff --git a/tools/parca-agent/Dockerfile.template b/tools/parca-agent/Dockerfile.template
--- a/tools/parca-agent/Dockerfile.template
+++ b/tools/parca-agent/Dockerfile.template
@@ -2,22 +2,27 @@
 
 ARG ref=main
 
-FROM --platform=amd64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
+FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
 ARG name
 ARG version
 RUN <<EOF
-curl --silent --location --fail "https://github.com/parca-dev/parca-agent/releases/download/v${version}/parca-agent_${version}_Linux_${arch}.tar.gz" \
-| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
-    parca-agent
-EOF
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
 
-FROM --platform=arm64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
-ARG name
-ARG version
-RUN <<EOF
-printenv
-set -x
-curl --silent --location --fail "https://github.com/parca-dev/parca-agent/releases/download/v${version}/parca-agent_${version}_Linux_${alt_arch}.tar.gz" \
+echo "### Downloading parca-agent ${version}"
+curl --silent --location --fail "https://github.com/parca-dev/parca-agent/releases/download/v${version}/parca-agent_${version}_Linux_${arch_suffix}.tar.gz" \
 | tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
     parca-agent
 EOF
diff --git a/tools/warp/Dockerfile.template b/tools/warp/Dockerfile.template
--- a/tools/warp/Dockerfile.template
+++ b/tools/warp/Dockerfile.template
@@ -2,20 +2,27 @@
 
 ARG ref=main
 
-FROM --platform=amd64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS download
+FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS download
 ARG name
 ARG version
 RUN <<EOF
-curl --silent --location --fail "https://github.com/minio/warp/releases/download/v${version}/warp_Linux_${arch}.tar.gz" \
-| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
-    warp
-EOF
+echo "### Setting architecture string for ${TARGETPLATFORM}"
+case "${arch}" in
+    x86_64)
+        export arch_suffix="${arch}"
+        ;;
+    aarch64)
+        export arch_suffix="${alt_arch}"
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture ${arch}."
+        exit 1
+        ;;
+esac
+echo "    Using ${arch_suffix}"
 
-FROM --platform=arm64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS download
-ARG name
-ARG version
-RUN <<EOF
-curl --silent --location --fail "https://github.com/minio/warp/releases/download/v${version}/warp_Linux_${alt_arch}.tar.gz" \
+echo "### Downloading warp ${version}"
+curl --silent --location --fail "https://github.com/minio/warp/releases/download/v${version}/warp_Linux_${arch_suffix}.tar.gz" \
 | tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
     warp
 EOF
